version: 2

sources:
    - name: staging
      database: data-zoomcamp-339218
      schema: trips_data_all

      tables: 
        - name: green_taxi_trips_external
        - name: yellow_taxi_trips
        - name: fhv_trips